### ISSUE TITLE
Support for newer version of Pixman

### ISSUE THREAD

**Issue by ngocdaothanh** [anoek/android-cairo#1]
To build with Pixman 0.25.2:

cpufeatures in Android NDK is needed.

Copy android-ndk/sources/android/cpufeatures directory to pixman-extra.

pixman.mk should be modified:
- LOCAL_CFLAGS:  add -Ijni/pixman-extra/cpufeatures and -include "limits.h"
- LIBPIXMAN_SRC: add pixman/pixman/pixman-noop.c and pixman-extra/cpufeatures/cpu-features.c

**Comment by anoek** [comment]
yukoba has been kind enough to bring us up to pixman 0.26 to address this
