### ISSUE TITLE
Status of this port

### ISSUE THREAD

**Issue by lilac** [anoek/android-cairo#6]
What is the status of this cairo porting? Is it complete? Is it possible or hard to port gtk+ to android based on this great work?

**Comment by anoek** [comment]
The status is "complete" as far as I've tested, at least for the version I last synced against (which is old now). 

GTK+ is a completely separate project though. I don't work with GTK+, but if it hasn't been ported already, it's probably a fairly involved process. I don't think the rendering / cairo layer would be hard to tie in and get going though, I imagine it'd be "everything else".
